import { useRef } from 'react'
import { motion, useReducedMotion, useScroll, useTransform } from 'motion/react'
import { Slug } from '@/components/SectionHead'
import { BloubMark } from '@/components/BloubMark'
import { ABOUT } from '@/lib/content'
import portrait from '@/assets/portrait.png'

const baseRise = {
  initial: { y: 24, opacity: 0 },
  whileInView: { y: 0, opacity: 1 },
  viewport: { once: true, margin: '-15%' },
  transition: { duration: 0.52, ease: [0.16, 1, 0.3, 1] as const },
}

export function About() {
  // a reveal that starts at opacity 0 is exactly the motion a reduced-motion
  // user declined — render the final state outright rather than waiting on
  // an intersection that may never come
  const reduced = useReducedMotion()
  const rise = reduced ? {} : baseRise

  /**
   * The portrait is the one image on the page, so it gets the depth: the frame
   * turns a few degrees as the section passes, and the photo drifts inside it
   * at a different rate. Two speeds on one object is what reads as parallax —
   * moving the whole thing would just be a slower scroll.
   *
   * Scroll-linked, so it plays on a phone exactly as it does on a desktop.
   * The `scale` is not decoration: the drift would otherwise pull the image
   * off its own clip and expose the tint underneath.
   */
  const frame = useRef<HTMLDivElement>(null)
  const { scrollYProgress } = useScroll({ target: frame, offset: ['start end', 'end start'] })
  const turn = {
    transformPerspective: 900,
    rotateY: useTransform(scrollYProgress, [0, 1], [7, -7]),
    rotateX: useTransform(scrollYProgress, [0, 1], [-5, 5]),
  }
  const drift = useTransform(scrollYProgress, [0, 1], ['7%', '-7%'])

  return (
    <section
      id="about"
      aria-labelledby="about-title"
      className="relative z-10 overflow-hidden bg-paper px-[clamp(1.25rem,5vw,5rem)] py-[clamp(6rem,14vh,12rem)] text-[oklch(0.145_0.008_62)]"
    >
      <Slug index="02" label="About" face="curieux" size={40} className="mb-16" />

      <div className="grid gap-12 lg:grid-cols-12 lg:gap-16">
        <motion.div {...rise} ref={frame} className="lg:col-span-5">
          {/* Portrait, still clipped to the `galet` (pebble) outline from the
              bloub shape kit. The image is a 1-bit Bayer dither generated by
              tools/dither.py: the dots live in the alpha channel, so the paper
              ground shows through and the studio backdrop drops out on its own.
              `pixelated` keeps the dots square as it scales up — smoothing them
              would defeat the whole effect. */}
          {/* a soft tint keeps the pebble outline readable — with a fully
              transparent ground the clip-path is applied but invisible, since
              the dither is a cutout */}
          <motion.div
            style={reduced ? undefined : turn}
            className="relative aspect-[4/5] w-full"
          >
            {/* the tint belongs inside the clip, not outside it — on the frame
                it would draw the pebble's bounding rectangle instead */}
            <div
              className="absolute inset-0 overflow-hidden bg-[oklch(0.928_0.010_84)]"
              style={{ clipPath: 'url(#clip-galet)' }}
            >
              <motion.img
                src={portrait}
                alt="Uday Chittala"
                width={275}
                height={375}
                style={reduced ? undefined : { y: drift, scale: 1.16 }}
                className="absolute inset-0 size-full object-cover object-top [image-rendering:pixelated]"
              />
            </div>
          </motion.div>
        </motion.div>

        <div className="lg:col-span-6 lg:col-start-7">
          <motion.h2
            {...rise}
            id="about-title"
            className="mb-8 text-[clamp(1.125rem,2vw,1.5rem)] leading-[1.4] tracking-[-0.01em]"
          >
            {ABOUT.lede}
            <BloubMark
              expression="heureux"
              className="ml-2 inline-block align-[-0.28em]"
              style={{ width: '1.6em', height: '1.6em' }}
            />
          </motion.h2>

          <motion.p {...rise} className="mb-16 max-w-[52ch] text-base leading-[1.7] opacity-70">
            {ABOUT.body}
          </motion.p>

          <motion.dl {...rise} className="border-t border-current/15">
            {ABOUT.facts.map((f) => (
              <div
                key={f.k}
                className="flex items-baseline gap-3 border-b border-current/15 py-4"
              >
                <dt className="mono-label shrink-0 opacity-60">{f.k}</dt>
                <span
                  aria-hidden="true"
                  className="min-w-6 flex-1 translate-y-[-3px] border-b border-dotted border-current/30"
                />
                <dd className="shrink-0 text-sm">{f.v}</dd>
              </div>
            ))}
          </motion.dl>
        </div>
      </div>
    </section>
  )
}
